### PR TITLE
Add experimental support for HTML templates

### PR DESCRIPTION
**Pull request by pieterbeulque**
**HTML**

```html
<template id="tpl-user-profile>
  <mr-user-profile class="user-profile>
    <img class="user-profile__image" />
    <span class="user-profile__name"></span>
  </mr-user-profile>
</template>
```

**Javascript**

```es6
const tpl = new Template('user-profile');

tpl.render({
  '.user-profile__image': {
    src: 'foo.jpg'
  },
  '.user-profile__name': 'Yves'
});```

### CODE REVIEW

**Comment by romainmenke** [comment]
I fully agree with the html part!

-----

`.user-profile__image`

I like using css selectors as keys.

-----

```
'.user-profile__image': {
    src: 'foo.jpg'
  },
```

`'.user-profile__name': 'Yves'`

This part is not consistent. Can we do something like this:

```
'.user-profile__name': {
   innerHtml : 'Yves'
},
```

**Comment by pieterbeulque** [comment]
You can do both.

`'.user-profile__name': 'Yves'`

is the same as

`'.user-profile__name': { textContent: 'Yves' }`

It's a shorthand because strings are probably the 90% use case.

**Comment by romainmenke** [comment]
Cool!

**Comment by yvesvanbroekhoven** [comment]
@pieterbeulque, this is based on this spec correct?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

**Comment by pieterbeulque** [comment]
Yes. It doesn't do anything magical either, just provides the `render({})` syntax to easily apply data to your template.

**Comment by pieterbeulque** [comment]
The example from the MDN docs would work like this using the helpers:

```es6
const tbody = document.querySelector('tbody');
const template = new Template('#productrow');

const row = template.render({
  'td:first-child': '1235646565',
  'td:last-child': 'Stuff'
});

tbody.appendChild(row);

const secondRow = template.render({
  'td:first-child': '0384928528',
  'td:last-child': 'Acme Kidney Beans'
});

tbody.appendChild(secondRow);
```

**Comment by fd** [comment]
Why reinvent the wheel instead of using something like [lit-html](https://github.com/PolymerLabs/lit-html)?

**Comment by pieterbeulque** [comment]
`lit-html` is a library to write your templates in JS utilising `<template>` somewhere in its inner workings (if I recall correctly). It's overkill for our use cases & enables bad practices for Mr. Henry client work (client-side rendering without considering server-side alternatives).

This is a wrapper class around HTML's `<template>`, which has a different use case.

Not to say `lit-html` is an impressive piece of code.

**Pull request merged**
